Address = "0xe7776De78740f28a96412eE5cbbB8f90896b11A5"
RPC = "https://bnbmev.ankr.com"
Website = "https://www.ankr.com"
Description = "Ankr Staking - makes staking, liquid staking, and other yield-earning opportunities easy and accessible to any crypto investor."
