# BSC Mainnet Builder List
# This file contains information about various builders on the BSC mainnet

[example]
Address = "0x04d6...73F197ccd186"
RPC = "https://rpc-builder.io"
Website = "https://example-builder.io"
Description = "This is the fastest builder on BSC network"
Contact = "example-builder@mail.com"
EVNNodeIDs = [
  "0011223344556677889900112233445566778899001122334455667788990000",
  "0011223344556677889900112233445566778899001122334455667788990011"
]

# builder: 48club
[48club-puissant-builder-ap]
Address = "0x48a5Ed9abC1a8FBe86ceC4900483f43a7f2dBB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"

[48club-puissant-builder-eu]
Address = "0x487e5Dfe70119C1b320B8219B190a6fa95a5BB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"

[48club-puissant-builder-us]
Address = "0x48FeE1BB3823D72fdF80671ebaD5646Ae397BB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"

[48club-puissant-builder-x]
Address = "0x48B4bBEbF0655557A461e91B8905b85864B8BB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"

[48club-puissant-builder-y]
Address = "0x4827b423D03a349b7519Dda537e9A28d31ecBB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"

[48club-puissant-builder-z]
Address = "0x48B2665E5E9a343409199D70F7495c8aB660BB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"

# builder: blockbus
[blockbus-builder-dublin]
Address = "0x3FC0c936c00908c07723ffbf2d536D6E0f62C3A4"
RPC = "https://bsc-dublin.blockbus.xyz"
Website = "https://www.blockbus.xyz/"
Description = "Scientific, Powerful, Efficient, Focused, Security, Privacy, BlockBus Builder."

[blockbus-builder-tokyo]
Address = "0x17e9F0D7E45A500f0148B29C6C98EfD19d95F138"
RPC = "https://bsc-tokyo.blockbus.xyz"
Website = "https://www.blockbus.xyz/"
Description = "Scientific, Powerful, Efficient, Focused, Security, Privacy, BlockBus Builder."

[blockbus-builder-virginia]
Address = "0x1319Be8b8Ec4AA81f501924BdCF365fBcAa8d753"
RPC = "https://bsc-virginia.blockbus.xyz"
Website = "https://www.blockbus.xyz/"
Description = "Scientific, Powerful, Efficient, Focused, Security, Privacy, BlockBus Builder."

# builder: blockrazor
[blockrazor-dublin]
Address = "0x5532CdB3c0c4278f9848fc4560b495b70bA67455"
RPC = "https://dublin.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"

[blockrazor-frankfurt]
Address = "0xBA4233f6e478DB76698b0A5000972Af0196b7bE1"
RPC = "https://frankfurt.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"

[blockrazor-nyc]
Address = "0x539E24781f616F0d912B60813aB75B7b80b75C53"
RPC = "https://nyc.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"

[blockrazor-relay]
Address = "0x49D91b1Ab0CC6A1591c2e5863E602d7159d36149"
RPC = "https://relay.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We provide an audited builder solution that ensures each block, transaction, and bundle is scrutinized by authoritative security agencies. Utilizing multiple strategies and advanced algorithms, we aim to build the most valuable and secure blocks. Visit our website for more information!"
Contact = "support@blockrazor.io"

[blockrazor-tokyo]
Address = "0x50061047B9c7150f0Dc105f79588D1B07D2be250"
RPC = "https://tokyo.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"

[blockrazor-virginia]
Address = "0x0557E8CB169F90F6eF421a54e29d7dd0629Ca597"
RPC = "https://virginia.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"

[blockrazor-x]
Address = "0x488e37fcB2024A5B2F4342c7dE636f0825dE6448"
RPC = "https://x.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We provide an audited builder solution that ensures each block, transaction, and bundle is scrutinized by authoritative security agencies. Utilizing multiple strategies and advanced algorithms, we aim to build the most valuable and secure blocks. Visit our website for more information!"
Contact = "support@blockrazor.io"

# builder: blocksmith
[blocksmith-ap]
Address = "0x6Dddf681C908705472D09B1D7036B2241B50e5c7"
RPC = "https://bsc-builder-report-ap.blocksmith.org/"
Website = "https://blocksmith.org"
Description = "We Empower Teams to Excel in DeFi Trading"
Contact = "dj@blocksmith.org"

[blocksmith-eu]
Address = "0x76736159984AE865a9b9Cc0Df61484A49dA68191"
RPC = "https://bsc-builder-report-eu.blocksmith.org/"
Website = "https://blocksmith.org"
Description = "We Empower Teams to Excel in DeFi Trading"

[blocksmith-us]
Address = "0x5054b21D8baea3d602dca8761B235ee10bc0231E"
RPC = "https://bsc-builder-report-us.blocksmith.org/"
Website = "https://blocksmith.org"
Description = "We Empower Teams to Excel in DeFi Trading"

# builder: bloxroute
[bloxroute-builder-dublin]
Address = "0xD4376FdC9b49d90e6526dAa929f2766a33BFFD52"
RPC = "https://bsc-builder-dublin.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-frankfurt]
Address = "0x2873fc7aD9122933BECB384f5856f0E87918388d"
RPC = "https://bsc-builder-frankfurt.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-japan]
Address = "0x432101856a330aafdeB049dD5fA03a756B3f1c66"
RPC = "https://bsc-builder-japan.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-nyc]
Address = "0x2B217a4158933AAdE6D6494e3791D454B4D13AE7"
RPC = "https://bsc-builder-nyc.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-relay]
Address = "0x0da52E9673529b6E06F444FbBED2904A37f66415"
RPC = "https://bsc-relay.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-singapore]
Address = "0xE1ec1AeCE7953ecB4539749B9AA2eEF63354860a"
RPC = "https://bsc-builder-singapore.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-virginia]
Address = "0x89434FC3a09e583F2cb4e47A8B8fe58De8BE6a15"
RPC = "https://bsc-builder-virginia.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

[bloxroute-builder-x]
Address = "0x10353562E662E333C0c2007400284e0e21cF74fF"
RPC = "https://bsc-builder-x.blxrbdn.com"
Website = "https://bloxroute.com"
Contact = "support@bloxroute.com"

# builder: darwinbuilder
[darwinbuilder-ap]
Address = "0xa6d6086222812eFD5292fF284b0F7ff2a2B86Af4"
RPC = "https://bsc-builder-ap.darwinbuilder.xyz"
Website = "https://darwinbuilder.xyz"
Description = "DarwinBuilder on BSC network"
Contact = "support@darwinbuilder.xyz"

[darwinbuilder-eu]
Address = "0x3265A3243ee84e667a73073504cA4CdeD1413D82"
RPC = "https://bsc-builder-eu.darwinbuilder.xyz"
Website = "https://darwinbuilder.xyz"
Description = "DarwinBuilder on BSC network"
Contact = "support@darwinbuilder.xyz"

[darwinbuilder-us]
Address = "0xdf11CD23992Fd48Cf2d245aC144010673275f285"
RPC = "https://bsc-builder-us.darwinbuilder.xyz"
Website = "https://darwinbuilder.xyz"
Description = "DarwinBuilder on BSC network"
Contact = "support@darwinbuilder.xyz"

# builder: inblock
[inblock-ap]
Address = "0x9a3234b450518fadA098388B88e00deCAd96ad38"
RPC = "https://bsc-ap.inblock.cc"
Website = "https://inblock.cc"
Description = "The efficient builder through global boost network, smart algorithms, and innovative architecture."
Contact = "support@inblock.cc"

[inblock-eu]
Address = "0xb49f86586a840AB9920D2f340a85586E50FD30a2"
RPC = "https://bsc-eu.inblock.cc"
Website = "https://inblock.cc"
Description = "The efficient builder through global boost network, smart algorithms, and innovative architecture."
Contact = "support@inblock.cc"

[inblock-us]
Address = "0x0F6D8b72F3687de6f2824903a83B3ba13c0e88A0"
RPC = "https://bsc-us.inblock.cc"
Website = "https://inblock.cc"
Description = "The efficient builder through global boost network, smart algorithms, and innovative architecture."
Contact = "support@inblock.cc"

# builder: jetbldr
[jetbldr-ap]
Address = "0x36CB523286D57680efBbfb417C63653115bCEBB5"
RPC = "https://rpc.bsc-ap.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-eu]
Address = "0x3aD6121407f6EDb65C8B2a518515D45863C206A8"
RPC = "https://rpc.bsc-eu.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-us]
Address = "0x345324dC15F1CDcF9022E3B7F349e911fb823b4C"
RPC = "https://rpc.bsc-us.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-dublin]
Address = "0xfd38358475078F81a45077f6e59dff8286e0dCA1"
RPC = "https://rpc.bsc.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-tokyo]
Address = "0x7F5fbFd8e2eB3160dF4c96757DEEf29E26F969a3"
RPC = "https://rpc.bsc.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-x]
Address = "0xA0Cde9891C6966fCe740817cc5576De2C669AB43"
RPC = "https://rpc.bsc.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-y]
Address = "0x69057994D714bDa413B450925A4a6EB057BfE8AC"
RPC = "https://rpc.bsc.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

[jetbldr-z]
Address = "0xE5Ae1c733df8a362abD56472aA4a4c817E9A9e84"
RPC = "https://rpc.bsc.jetbldr.xyz"
Website = "https://jetbldr.xyz/"
Description = "JetBuilder on BSC network"
Contact = "hi@jetbldr.xyz"

# builder: nodereal
[nodereal-ap]
Address = "0x79102dB16781ddDfF63F301C9Be557Fd1Dd48fA0"
RPC = "https://bsc-mainnet-builder-ap.nodereal.io"
Website = "https://nodereal.io/"
Description = "Advanced Infrastructure Provider for EVM blockchains."

[nodereal-eu]
Address = "0xd0d56b330a0dea077208b96910ce452fd77e1b6f"
RPC = "https://bsc-mainnet-builder-eu.nodereal.io"
Website = "https://nodereal.io/"
Description = "Advanced Infrastructure Provider for EVM blockchains."

[nodereal-us]
Address = "0x4f24ce4cd03a6503de97cf139af2c26347930b99"
RPC = "https://bsc-mainnet-builder-us.nodereal.io"
Website = "https://nodereal.io/"
Description = "Advanced Infrastructure Provider for EVM blockchains."

# builder: xzbuilder
[xzbuilder]
Address = "0x812720cb4639550D7BDb1d8F2be463F4a9663762"
RPC = "https://rpc.xzbuilder.com/"
Website = "https://xzbuilder.com/"
Description = "XZBuilder - Max profit builder for BSC Blockchain"