Address = "0x487e5Dfe70119C1b320B8219B190a6fa95a5BB48"
RPC = "https://puissant-bsc.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"