Address = "0x48B4bBEbF0655557A461e91B8905b85864B8BB48"
RPC = "https://puissant-bsc.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"