Address = "0x48FeE1BB3823D72fdF80671ebaD5646Ae397BB48"
RPC = "https://puissant-bsc.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"