Address = "0x1319Be8b8Ec4AA81f501924BdCF365fBcAa8d753"
RPC = "https://bsc-virginia.blockbus.xyz"
Website = "https://www.blockbus.xyz/"
Description = "Scientific, Powerful, Efficient, Focused, Security, Privacy, BlockBus Builder."