Address = "0x17e9F0D7E45A500f0148B29C6C98EfD19d95F138"
RPC = "https://bsc-tokyo.blockbus.xyz"
Website = "https://www.blockbus.xyz/"
Description = "Scientific, Powerful, Efficient, Focused, Security, Privacy, BlockBus Builder."