Address = "0x3265A3243ee84e667a73073504cA4CdeD1413D82"
RPC = "https://bsc-builder-eu.darwinbuilder.xyz"
Website = "https://darwinbuilder.xyz"
Description = "DarwinBuilder on BSC network"
Contact = "support@darwinbuilder.xyz"
