Address = "0xdf11CD23992Fd48Cf2d245aC144010673275f285"
RPC = "https://bsc-builder-us.darwinbuilder.xyz"
Website = "https://darwinbuilder.xyz"
Description = "DarwinBuilder on BSC network"
Contact = "support@darwinbuilder.xyz"
