Address = "0x9a3234b450518fadA098388B88e00deCAd96ad38"
RPC = "https://bsc-ap.inblock.cc"
Website = "https://inblock.cc"
Description = "The efficient builder through global boost network, smart algorithms, and innovative architecture."
Contact = "support@inblock.cc"