Address = "0x4f24ce4cd03a6503de97cf139af2c26347930b99"
RPC = "https://bsc-mainnet-builder-us.nodereal.io"
Website = "https://nodereal.io/"
Description = "Advanced Infrastructure Provider for EVM blockchains."