Address = "0x79102dB16781ddDfF63F301C9Be557Fd1Dd48fA0"
RPC = "https://bsc-mainnet-builder-ap.nodereal.io"
Website = "https://nodereal.io/"
Description = "Advanced Infrastructure Provider for EVM blockchains."